/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookDotepubRouteImport } from './routes/book[.]epub'
import { Route as ApiConvertRouteImport } from './routes/api/convert'
import { Route as ApiEpubRouteImport } from './routes/api/epub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDotepubRoute = BookDotepubRouteImport.update({
  id: '/book.epub',
  path: '/book.epub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpubRoute = ApiEpubRouteImport.update({
  id: '/api/epub',
  path: '/api/epub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book.epub': typeof BookDotepubRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/epub': typeof ApiEpubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book.epub': typeof BookDotepubRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/epub': typeof ApiEpubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book.epub': typeof BookDotepubRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/epub': typeof ApiEpubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book.epub' | '/api/convert' | '/api/epub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book.epub' | '/api/convert' | '/api/epub'
  id: '__root__' | '/' | '/book.epub' | '/api/convert' | '/api/epub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookDotepubRoute: typeof BookDotepubRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiEpubRoute: typeof ApiEpubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book.epub': {
      id: '/book.epub'
      path: '/book.epub'
      fullPath: '/book.epub'
      preLoaderRoute: typeof BookDotepubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/epub': {
      id: '/api/epub'
      path: '/api/epub'
      fullPath: '/api/epub'
      preLoaderRoute: typeof ApiEpubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookDotepubRoute: BookDotepubRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiEpubRoute: ApiEpubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
